server:
  port: 9092
spring:
  application:
    #应用的名称，可选
    name: searchservice
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/knowledge_back?characterEncoding=utf-8&useSSL=false
      username: root
      password: 1234
  servlet:
    multipart:
      max-file-size: 20MB  #图片视频限制为20mb
      max-request-size: 20MB
  main:
    allow-bean-definition-overriding: true  #允许datasource这个bean被重复定义
  redis:
    host: 47.97.230.100
    port: 6379
    password: 1234
    lettuce: #连接池配置
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  cache:
    redis:
      time-to-live: 300     #指定所有的缓存的时间是5分钟
    type: redis
    cache-names: knowledge_backCache

#  rabbitmq:
#    host: 47.97.230.100
#    port: 5672
#    username: root
#    password: 1234
#    virtual-host: /
  jackson:
    parser:
      ALLOW-NUMERIC-LEADING-ZEROS: true  #运行JSON传递请求参数以0开头的正整数（在验证码中出现）。

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #这个可以帮忙打印mp运行时的sql日志
  global-config:
    db-config:
      id-type: ASSIGN_ID
#mybatis:
#  config-location: classpath:mybatis-config.xml

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

knowledge_back:
  articleFolderPath: ./article/
  videoFolderPath: ./video/
es:
  host: 47.97.230.100
  port: 9200